---
title: "Para_presentacion"
format: html
editor: visual
---

## Quarto



```{r}
library(survival)
tabla=as.table(survexp.us[,,"2004"])

knitr::kable(tabla, booktabs = TRUE, digits = 5,format.args = list(scientific = FALSE),
             format = "simple",
             caption="Tasas de riesgo (hazard rates) de hombres y mujeres por edad para el año 2004")
```


```{r}
tm <- c(0, # birth
        1:110) # subsequent years
hazMale <- survexp.us[,"male","2004"] # 2004 males
hazFemale <- survexp.us[,"female","2004"] # 2004 females
tm.diff <- diff(tm)
survMale <- exp(-cumsum(hazMale*tm.diff)*365.24)
survFemale <- exp(-cumsum(hazFemale*tm.diff)*365.24)

# Figure 2.1.2 log hazard and survival for US males and females in 2004
par(mfrow=c(2,1),    # two rows and one column of plots
    mar=c(4.2,5,2,2))  # set margins for the lower, left, top, and righ of each plot

logHazMale <- log(hazMale)
logHazFemale <- log(hazFemale)    

plot(logHazMale ~ tm[-1], type="l",
     xlab="Age in years",           # x axis label
     ylab="Hazard",col="blue",      # y azis label
     lwd=2,                         # double line width
     las=1,                         # make y axis labels perpendicular to axis
     axes=F, cex.lab=1.3, cex.axis=1.3)     # make blue line solid
lines(logHazFemale ~ tm[-1],type="l", 
      col="red",lwd=2, lty=2)   # add a red dashed line to the plot

yyLabs <- c(1e-07, 1e-06, 1e-05, 1e-04, 1e-03, 1e-02)
yyLabsLog <- log(yyLabs)
axis(2, at=yyLabsLog, labels=c(expression(10^-7), expression(10^-6), 
  expression(10^-5), expression(10^-4), expression(10^-3), expression(10^-2)), las=1)  
axis(1, cex.axis=1.3)   
legend("bottomright", legend=c("males","females"),
       lty=c(1,2), col=c("blue","red"), lwd=2, cex=1.3)
title("Hazards for US males and females in 2004")


tm.diff <- diff(tm)         # same length as "tm"
survMale <- exp(-cumsum(hazMale*tm.diff)*365.24)         # survival probs for males
survFemale <- exp(-cumsum(hazFemale*tm.diff)*365.24)     # survival probs for females
#windows(width=7,height=5)
plot(survMale ~ tm[-1],type="l",          # lower case "L" indicates line plot
     xlab="Age in years",             # x axis label
     ylab="Survival probability",     # y azis label
     col="blue",                      # line color
     lwd=2,                           # double line width
     las=1,                           # make y axis labels perpendicular to axis
     ylim=c(0,1), cex.lab=1.3, cex.axis=1.3)       # y axis limit ranges from 0 to 1

lines(survFemale ~ tm[-1], col="red", lwd=2, lty=2)    # add a red dashed line to the plot
legend("bottomleft", legend=c("males","females"),
       lty=c(1,2), col=c("blue","red"), lwd=2, cex=1.3)
title("Survival of US males and females in 2004")


```


```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
